### ISSUE TITLE
what to do when `ppl=-nan`?

### ISSUE THREAD

**Issue by geovedi** [neubig/nmt-tips#3]
so I experimenting subwords units to minimise vocabs, but always end-up with `ppl=-nan`. 

tried to avoid it is by making sure the unbalanced data removed using tools like `filter-length.pl` and lowering learning rate, but still no luck.

**Comment by neubig** [comment]
If you can provide the data and exact command that you ran, I might be able
to debug.

Graham

On Jan 6, 2017 4:32 AM, "Jim Geovedi" <notifications@github.com> wrote:

so I experimenting subwords units to minimise vocabs, but always end-up
with ppl=-nan.

tried to avoid it is by making sure the unbalanced data removed using tools
like filter-length.pl and lowering learning rate, but still no luck.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/neubig/nmt-tips/issues/3>, or mute the thread

**Comment by geovedi** [comment]
sure, i'll send it privately to your @cs.cmu.edu e-mail address.

**Comment by geovedi** [comment]
looks like i have a bad data. works fine on my other data.
